@startuml
title Inicio de sesión
actor Admin
actor Asesor

Asesor - (Iniciar sesión como asesor)
Admin -left- (Iniciar sesión como administrador)

(Iniciar sesión como asesor).->(Cerrar sesión)
(Iniciar sesión como administrador).->(Cerrar sesión)
'note right of Admin : This is an example.

'note right of (Use)
'A note can also
'be on several lines
'end note

'note "This note is connected\nto several objects." as N2
'(Start) .. N2
'N2 .. (Use)
@enduml