@startuml
title Módulo asesores del administrador

actor Administrador as Admin

(Asesores) as (ase)

(Crear asesor) as (cas)
(Listado asesores) as (ass)

'Primer nivel

Admin - (ase)
(ase)<.-(cas)
(ase)<.-(ass)



@enduml