@startuml
title Módulo cooperadores del administrador

actor Administrador as Admin

(Cooperadores) as (coo)

(Crear cooperador) as (cc)
(Listado cooperadores) as (lc)

'Primer nivel

Admin - (coo)
(coo)<.-(cc)
(coo)<.-(lc)

@enduml