@startuml
title Módulo practicantes del administrador

actor Administrador as Admin

(Practicantes) as (pra)

(Crear practicante) as (cp)
(Listado practicantes) as (lp)

'Primer nivel

Admin - (pra)
(pra)<.-(cp)
(pra)<.-(lp)



@enduml